# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 190b735ffee77acfb4367e8cf689d3a7215ce80eab79c3c3ce18877f33c625d762be7178af90d355c283161ea93902b1d7ac942877f101d6524e110edd71c933

test:
  secret_key_base: f124f1cb54078b6409a64becd26c4efdf5a84894b8ed81558df00c0f8cfa5df2d330d1a12913c2197780988a4f37188369111be688d1bdeb2c99d60927eda07f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
